
# test:
#    path: /test/{age<\d+>?20}
#    controller: App\Controller\TestController::test
#    methods: [GET, POST]
#    host: localhost
#    schemes: [https, http]
#    # defaults:
#    #    age: 10
#    # requirements: 
#    #    age: \d+